CREATE TABLE IF NOT EXISTS courses (
  user_id INT FOREIGN KEY,
  course_id INT FOREIGN KEY,
  course_code VARCHAR(255) NOT NULL,
  instructor_id INT FOREIGN KEY,
  class_period INT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
