import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("office_hours").del();

  // Inserts seed entries
  await knex("office_hours").insert([
    {
      course_id: 8371,
      host: "Shreyas Adireddy",
      mode: "remote",
      link: "https://discord.gg/eXU9Q7J8hm",
      start_time: "09:35:00",
      end_time: "10:25:00",
      day: "monday",
    },
    {
      course_id: 8371,
      host: "Chris Tressler",
      mode: "in-person",
      location: "MALA5200",
      start_time: "09:35:00",
      end_time: "10:25:00",
      day: "tuesday",
    },
    {
      course_id: 8371,
      host: "Shreyas Adireddy",
      mode: "remote",
      link: "https://discord.gg/eXU9Q7J8hm",
      start_time: "09:35:00",
      end_time: "10:25:00",
      day: "wednesday",
    },
    {
      course_id: 8371,
      host: "Tony Wong",
      mode: "remote",
      link: "https://discord.gg/eXU9Q7J8hm",
      start_time: "09:35:00",
      end_time: "10:25:00",
      day: "thursday",
    },
    {
      course_id: 8371,
      host: "Anna Albertelli",
      mode: "in-person",
      location: "MALA5200",
      start_time: "09:35:00",
      end_time: "10:25:00",
      day: "friday",
    },
    {
      course_id: 7699,
      host: "Adam Bracci",
      mode: "remote",
      link: "https://discord.gg/eXU9Q7J8hm",
      start_time: "10:40:00",
      end_time: "11:30:00",
      day: "monday",
    },
    {
      course_id: 7699,
      host: "Jackie Wang",
      mode: "in-person",
      location: "MALA5200",
      start_time: "10:40:00",
      end_time: "11:30:00",
      day: "tuesday",
    },
    {
      course_id: 7699,
      host: "Adam Benali",
      mode: "in-person",
      location: "MALA5200",
      start_time: "10:40:00",
      end_time: "11:30:00",
      day: "wednesday",
    },
    {
      course_id: 7699,
      host: "Tony Wong",
      mode: "remote",
      link: "https://discord.gg/eXU9Q7J8hm",
      start_time: "10:40:00",
      end_time: "11:30:00",
      day: "thursday",
    },
    {
      course_id: 7699,
      host: "Anna Albertelli",
      mode: "in-person",
      location: "MALA5200",
      start_time: "10:40:00",
      end_time: "11:30:00",
      day: "friday",
    },
    {
      course_id: 7699,
      host: "Shane Ferrell",
      mode: "in-person",
      location: "MALA5200",
      start_time: "11:45:00",
      end_time: "12:35:00",
      day: "thursday",
    },
    {
      course_id: 7699,
      host: "Shane Ferrell",
      mode: "in-person",
      location: "MALA5200",
      start_time: "12:50:00",
      end_time: "13:40:00",
      day: "wednesday",
    },
    {
      course_id: 8371,
      host: "Ethan King",
      mode: "in-person",
      location: "MALA5200",
      start_time: "13:55:00",
      end_time: "14:45:00",
      day: "monday",
    },
    {
      course_id: 8371,
      host: "Brandon Barker",
      mode: "in-person",
      location: "MALA5200",
      start_time: "13:55:00",
      end_time: "14:45:00",
      day: "tuesday",
    },
    {
      course_id: 8371,
      host: "Adam Hassan",
      mode: "in-person",
      location: "MALA5200",
      start_time: "13:55:00",
      end_time: "14:45:00",
      day: "friday",
    },
    {
      course_id: 8371,
      host: "Chris Tressler",
      mode: "in-person",
      location: "MALA5200",
      start_time: "16:05:00",
      end_time: "16:55:00",
      day: "monday",
    },
    {
      course_id: 8371,
      host: "Brandon Barker",
      mode: "in-person",
      location: "MALA5200",
      start_time: "16:05:00",
      end_time: "16:55:00",
      day: "wednesday",
    },
    {
      course_id: 8371,
      host: "Adam Bracci",
      mode: "remote",
      link: "https://discord.gg/eXU9Q7J8hm",
      start_time: "16:05:00",
      end_time: "16:55:00",
      day: "friday",
    },
  ]);
}